project_name: terraform-provider-ecloud
before:
  hooks:
    - go mod download
builds:
- env:
  - CGO_ENABLED=0
  - GO111MODULE=on
  goos:
    - windows
    - linux
    - darwin
  goarch:
    - amd64
    - arm
    - arm64
archives:
- format_overrides: 
  - goos: windows 
    format: zip
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
release:
  disable: true
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'

